### ISSUE TITLE
pypbc on Windows OS

### ISSUE THREAD

**Issue by Leepay** [debatem1/pypbc#10]
Anyone import pypbc on Windows OS successfully？ Could you please tell me how to do it? or if anyone has idea on it, please tell me. 
Thanks!

**Comment by zjxyyds0307** [comment]
hello,I have something want to ask you.Can you give me a email or a WeChat or a QQ num? My email is zjxyyds0307@qq.com.My QQ num is 3621981609.My WeChat is zjxyyds0307. Thanks So much.

**Comment by Leepay** [comment]
> hello,I have something want to ask you.Can you give me a email or a WeChat or a QQ num? My email is [zjxyyds0307@qq.com.My](mailto:zjxyyds0307@qq.com.My) QQ num is 3621981609.My WeChat is zjxyyds0307. Thanks So much.

I managed importing pypbc on Ubuntu, commands:(I wrote comments in Chinese)
```
安装依赖
>sudo apt-get install M4
>sudo apt-get install flex
>sudo apt-get install bison
安装GMP
>wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz
>lzip -d gmp-6.1.2.tar.lz
>tar -xvf gmp-6.1.2.tar
>cd gmp-6.1.2
>./configure
>make
>make check
>sudo make install
安装PBC
>wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
>tar -xvf pbc-0.5.14.tar.gz
>cd pbc-0.5.14
>./configure
>make
>sudo make install
安装pypbc
>git clone https://github.com/debatem1/pypbc
>sudo python3 setup.py install(如果报错Nomodulenameddistutils.core:sudo apt-get install python3-pip)
>sudo pip3 install pypbc
(安装之后import如果libpbc.so.1: cannot open shared object file: No such file or directory
这个问题是出现在安装pbc的时候所出现的外部动态文件无法被索引到，这种情况下，可以进行如下操作：
vim ld.so.conf.d
然后在ld.so.conf.d中添加你libpbc.so.1的路径，/usr/local/lib
之后 sudo ldconfig)
```
Environment:
Ubuntu: 18.04,
Python 3.6

**Comment by zjxyyds3r7** [comment]
> > hello,I have something want to ask you.Can you give me a email or a WeChat or a QQ num? My email is [zjxyyds0307@qq.com.My](mailto:zjxyyds0307@qq.com.My) QQ num is 3621981609.My WeChat is zjxyyds0307. Thanks So much.
> 
> I managed importing pypbc on Ubuntu, commands:(I wrote comments in Chinese)
> 
> ```
> 安装依赖
> >sudo apt-get install M4
> >sudo apt-get install flex
> >sudo apt-get install bison
> 安装GMP
> >wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz
> >lzip -d gmp-6.1.2.tar.lz
> >tar -xvf gmp-6.1.2.tar
> >cd gmp-6.1.2
> >./configure
> >make
> >make check
> >sudo make install
> 安装PBC
> >wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
> >tar -xvf pbc-0.5.14.tar.gz
> >cd pbc-0.5.14
> >./configure
> >make
> >sudo make install
> 安装pypbc
> >git clone https://github.com/debatem1/pypbc
> >sudo python3 setup.py install(如果报错Nomodulenameddistutils.core:sudo apt-get install python3-pip)
> >sudo pip3 install pypbc
> (安装之后import如果libpbc.so.1: cannot open shared object file: No such file or directory
> 这个问题是出现在安装pbc的时候所出现的外部动态文件无法被索引到，这种情况下，可以进行如下操作：
> vim ld.so.conf.d
> 然后在ld.so.conf.d中添加你libpbc.so.1的路径，/usr/local/lib
> 之后 sudo ldconfig)
> ```
> 
> Environment: Ubuntu: 18.04, Python 3.6

I run these commands successfully, but when I run the script 'test.py', I get an error 'SystemError: <built-in function len> returned a result with an error set' on line 311, I don't know why and what should I do for it?
