### ISSUE TITLE
How can I get the 'm' from e(g,g)^m?

### ISSUE THREAD

**Issue by wangqi01** [debatem1/pypbc#5]
If I get e(g,g)^m, and I know e(g,g), then how can I get 'm' ?

**Comment by haidaner** [comment]
Knowing the 'm' corresponds to a calculation of the discrete logarithm for generate e(g,g). 
This is believed to be hard.
Hence in most encryption schemes, the plaintext space where 'm' has been chosen from is limited, allowing brute force (or advanced algorithm like the baby-step giant-step algorithm) to get 'm' from e(g,g)^m.

**Comment by wangqi01** [comment]
Thanks for your kind response, the discrete logarithm problem is hard for big integers, but possible for a limited message. But the current problem is that I could not find the method to map the e(g,g) to a integer in this python library, I will be grateful if you could help me.

**Comment by wangqi01** [comment]
> Knowing the 'm' corresponds to a calculation of the discrete logarithm for generate e(g,g).
> This is believed to be hard.
> Hence in most encryption schemes, the plaintext space where 'm' has been chosen from is limited, allowing brute force (or advanced algorithm like the baby-step giant-step algorithm) to get 'm' from e(g,g)^m.



> Knowing the 'm' corresponds to a calculation of the discrete logarithm for generate e(g,g).
> This is believed to be hard.
> Hence in most encryption schemes, the plaintext space where 'm' has been chosen from is limited, allowing brute force (or advanced algorithm like the baby-step giant-step algorithm) to get 'm' from e(g,g)^m.

Thanks for your kind response, the discrete logarithm problem is hard for big integers, but possible for a limited message. But the current problem is that I could not find the method to map the e(g,g) to a integer in this python library, I will be grateful if you could help me.

**Comment by haidaner** [comment]
AFAIK there is no such function implemented in (py)PBC, so you have to implement it by yourself. 
For bruteforche, your solution could be something like that:

```
c = e(g,g)^m #You only have c and want to know m
for m_candidate in msgSpace: # Try all candidates in msgSpace
  if e(g,g)^m_candidate == c: #  Check if this candidate is correct
    return m_candidate # you found the correct m 
return None # The plaintext is not contained in the msgSpace

```

**Comment by wangqi01** [comment]
Thanks a lot!
